package com.example.cinema_ticket_booking.controller;

import com.example.cinema_ticket_booking.model.Session;
import com.github.fge.jsonpatch.JsonPatch;
import com.github.fge.jsonpatch.mergepatch.JsonMergePatch;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;

@Tag(name = "Session Management", description = "API for creating, searching, updating, and deleting movie sessions")
@RequestMapping("/sessions")
public interface SessionControllerApi {
    @Operation(
            summary = "Get all sessions",
            description = "Returns a list of sessions with support for date filtering and pagination."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "List retrieved successfully",
                    content = @Content(mediaType = "application/json", schema = @Schema(implementation = Session.class)))
    })
    @GetMapping
    List<Session> sessions(
            @Parameter(description = "Filter by date (YYYY-MM-DD)")
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date,

            @Parameter(description = "Page number (0..N)")
            @RequestParam(defaultValue = "0") int page,

            @Parameter(description = "Page size")
            @RequestParam(defaultValue = "3") int size
    );

    @Operation(
            summary = "Get session by ID",
            description = "Returns full details of a specific session."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Session found",
                    content = @Content(mediaType = "application/json", schema = @Schema(implementation = Session.class))),
            @ApiResponse(responseCode = "404", description = "Session not found", content = @Content)
    })
    @GetMapping("/{id}")
    ResponseEntity<Session> findById(
            @Parameter(description = "Session ID") @PathVariable Long id
    );

    @Operation(
            summary = "Update or Create session",
            description = "Updates an existing session or creates a new one with the specified ID."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Session updated or created successfully",
                    content = @Content(mediaType = "application/json", schema = @Schema(implementation = Session.class))),
            @ApiResponse(responseCode = "400", description = "ID mismatch between URL path and request body", content = @Content)
    })
    @PutMapping("/{id}")
    ResponseEntity<Session> save(
            @Parameter(description = "Session ID") @PathVariable Long id,
            @RequestBody Session sessionDto
    );

    @Operation(
            summary = "Create a new session",
            description = "Creates a new session. The ID is generated by the server."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Session created successfully",
                    content = @Content(mediaType = "application/json", schema = @Schema(implementation = Session.class))),
            @ApiResponse(responseCode = "400", description = "Request body contains an ID (ID must be null for creation)", content = @Content)
    })
    @PostMapping
    ResponseEntity<Session> create(
            @RequestBody Session sessionDto
    );

    @Operation(
            summary = "Delete session",
            description = "Deletes a session by its ID."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "Session deleted successfully")
    })
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteByI(
            @Parameter(description = "Session ID") @PathVariable Long id
    );

    @Operation(
            summary = "Часткове оновлення (PATCH)",
            description = """
                    Оновлює окремі поля сеансу. Підтримує два стандарти залежно від Content-Type:
                    
                    1. **JSON Patch (RFC 6902)**
                       Content-Type: application/json-patch+json
                       Передається масив операцій (add, remove, replace).
                    
                    2. **JSON Merge Patch (RFC 7386)**
                       Content-Type: application/merge-patch+json
                       Передається частковий JSON об'єкт з новими значеннями.
                    """,
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    content = {
                            @Content(
                                    mediaType = "application/json-patch+json",
                                    schema = @Schema(implementation = JsonPatch.class),
                                    examples = @io.swagger.v3.oas.annotations.media.ExampleObject(
                                            name = "JSON Patch Example",
                                            value = "[{\"op\": \"replace\", \"path\": \"/hallNumber\", \"value\": 5}]"
                                    )
                            ),
                            @Content(
                                    mediaType = "application/merge-patch+json",
                                    schema = @Schema(implementation = JsonMergePatch.class),
                                    examples = @io.swagger.v3.oas.annotations.media.ExampleObject(
                                            name = "Merge Patch Example",
                                            value = "{\"hallNumber\": 5}"
                                    )
                            )
                    }
            )
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Сеанс оновлено",
                    content = @Content(mediaType = "application/json", schema = @Schema(implementation = Session.class))),
            @ApiResponse(responseCode = "400", description = "Некоректний формат патчу", content = @Content),
            @ApiResponse(responseCode = "404", description = "Сеанс не знайдено", content = @Content)
    })
    @PatchMapping(path = "/{id}", consumes = "application/json-patch+json")
    ResponseEntity<Session> jsonPatch(
            @Parameter(description = "ID сеансу") @PathVariable Long id,
            @RequestBody JsonPatch patch
    );

    @PatchMapping(path = "/{id}", consumes = "application/merge-patch+json")
    ResponseEntity<Session> jsonMergePatch(
            @Parameter(hidden = true) @PathVariable Long id,
            @RequestBody JsonMergePatch patch
    );

}
